name: Composer Audit

on:
  workflow_call:
    inputs:
      php-version:
        type: string
        required: true
      issue_labels:
        type: string
        default: vulnerability,composer
    secrets:
      AUDIT_ACTION_PAT:
        required: true

jobs:
  audit:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN_PAT: ${{ secrets.AUDIT_ACTION_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run composer audit
        id: audit
        run: |
          echo "Running composer audit..."
          AUDIT_OUTPUT=$(composer audit 2>&1 || true)
          echo "$AUDIT_OUTPUT" > audit.txt

          echo "audit_output<<EOF" >> $GITHUB_OUTPUT
          echo "$AUDIT_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          VULNS=$(echo "$AUDIT_OUTPUT" | grep -c "Package" || true)
          echo "vulns=$VULNS" >> $GITHUB_OUTPUT

      - name: Check for existing vulnerability issue
        id: find_issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN_PAT }}
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: '${{ inputs.issue_labels }}',
              state: 'open'
            });
            return issues.data.length ? issues.data[0].number : null;
          result-encoding: string

      - name: Create issue if vulnerabilities exist
        if: steps.audit.outputs.vulns != '0'
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN_PAT }}
          script: |
            const auditOutput = `${{ steps.audit.outputs.audit_output }}`.trim();
            if (!auditOutput) return;